name: assignment_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

#For using cupertino icons
cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
  
    sdk: flutter


  http: ^0.13.6   
  html: ^0.15.0              
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets :
    - images/
